project:
  type: website

website:
  favicon: logo.svg
  navbar:
    search: false
    title: false
    left:
      - href: index.qmd
        text: "Home"
      - sidebar:how
    tools:
      - icon: linkedin
        href:  https://linkedin.com/in/victor2wy/
      - icon: github
        href:  https://github.com/wvictor14/labourcan/
  sidebar:
    - id: how
      title: "How"
      style: "floating"
      contents:
        - 02_develop_visualization.qmd
        - 03_things_that_didnt_work.qmd
        - 01_develop_data_processing.qmd
      alignment: center